### ISSUE TITLE
tanya :D

### ISSUE THREAD

**Issue by ardani** [atherlangga/dddtix#1]
mas mau tanya , itu sample ddd part 1 di model.php kok interface sebagai contract kok kosong ?
bukane interface itu digunakan untuk mengkomunikasikan beberapa class dengan implement yang sama ?

**Comment by atherlangga** [comment]
Itu karena memang tujuan utama saya untuk menandai mana obyek `Entity` dan mana obyek yang `ValueObject`. Dan untuk mencapai tujuan tersebut, menurut saya yang paling cocok adalah memakai PHP Interface, walaupun tidak ada isinya.

Semoga menjawab pertanyaan :).
